name = "gamecoach"
compatibility_date = "2024-09-23"
compatibility_flags = ["nodejs_compat"]
pages_build_output_dir = ".vercel/output/static"

[[d1_databases]]
binding = "DB"
database_name = "gamecoach-db"
database_id = "dda2d31c-d1de-4ca9-8789-917da0d4902d"

[[kv_namespaces]]
binding = "KV"
id = "bad1c1728ca34dcbaa4fd5f4338fb69c"
